### ISSUE TITLE
Logged-in front-end users

### ISSUE THREAD

**Issue by nilshoerrmann** [symphonists/tracker#34]
When creating or updating entries from the front-end, Tracker creates records similar to this one:

> A front-end user updated  `Ohne Titel` in the `Filme` section.

This is just fine, as long as the front-end user is unknown but it's not very helpful when the front-end user is also logged into the backend. In this case I'd expect a different message like:

> Nils Hörrmann updated `Ohne Titel` in the `Filme` section from the front-end.

**Comment by michael-e** [comment]
I thought that you (!) already fixed it: https://github.com/symphonists/tracker/issues/15

Looking at #35, maybe there is a more general issue? Not logging usernames properly?

**Comment by nilshoerrmann** [comment]
No, that's about something different:
I'm talking about untracked Symphony authors on the front-end, not Members users.

**Comment by michael-e** [comment]
Ah, OK. I misunderstood.

**Comment by nitriques** [comment]
Well, a quick looks at the code reveals that no calls are being made to `isLoggued()` or `login()` so I would suspect that's normal. I often have an event that do call it, maybe that's why I do not see it ?

Also, because the code uses the old member accessor (https://github.com/symphonycms/symphony-2/wiki/Migration-Guide-to-2.5-for-Developers#properties) here https://github.com/symphonists/tracker/blob/master/extension.driver.php#L311 and here https://github.com/symphonists/tracker/blob/master/extension.driver.php#L549

**Comment by nilshoerrmann** [comment]
Maybe this extension is approaching users incorrectly. I think initially, it just expected one kind of user, either Symphony author or front-end user. With the changes in #15, Members users have been added but the solution is incomplete because it doesn't consider multiple role combinations.

We actually have three levels of user roles that Tracker should always detect before creating its message:

- Symphony authors
- Members users
- front-end users

It's possible to have differrent combinations:

- Symphony author + Members user
- Symphony author + front-end user
- Members users
- Symphony author
- front-end user

Currently the extension doesn't handle all of these combinations. We should also have message like the following:

> Nils Hörrmann created `Test` in the `Blog` section as front-end member Nils
